### ISSUE TITLE
Replace solc compiler for zksolc

### ISSUE THREAD

**Issue by mationorato** [lambdaclass/zkethers-rs#1]
Replace and refactor the code to remove the solc compiler and add the zksolc version so the compilation process is seamless for Ethereum developers.

**Comment by IAvecilla** [comment]
At first, the idea was to replace the compiler call in `ethers-rs`. After discussing, this task will be done directly on our [new lib](https://github.com/lambdaclass/zksync-web3-rs) for simplicity of the code base and for debugging purposes.
